import Accordion from './accordion/index.js';
import Carousel from './carousel/index.js';
import Confirm from './confirm/index.js';
import Icon from './icon/index.js';
import Image from './image/index.js';
import Input from './input/index.js';
import Loading from './loading/index.js';
import Mask from './mask/index.js';
import Ratio from './ratio/index.js';
import Slider from './slider/index.js';
import Message from './message/index.js';
import Radio from './radio/index.js';
import Upload from './upload/index.js';
import Tag from './tag/index.js';
export { Accordion, Carousel, Confirm, Icon, Image, Input, Loading, Mask, Ratio, Slider, Message, Radio, Upload, Tag };
